XRTK/com.xrtk.sdk

XRTK.SDK/Assets/XRTK.SDK/DefaultProfiles/DefaultMixedRealityToolkitConfigurationProfile.asset
XRTK.SDK/Assets/XRTK.SDK/Features/UX/Scripts/Pointers/MousePointer.cs
XRTK.SDK/Assets/XRTK.SDK/Inspectors/UX/Pointers/MousePointerInspector.cs
XRTK.SDK/Assets/XRTK.SDK/package.json
XRTK.SDK/Packages/manifest.json

- Updated Mouse Speed settings.
- Added Camera System to main configuration profile
- FIxes https://github.com/XRTK/SDK/issues/2

Updated XRTK.Core

---

XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json

- also bumped version to 0.1.5

Dev package updates

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Prefabs/Pointers/DefaultControllerPointer.prefab
XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/DefaultPointerLine.mat

- updated material
- updated prefab

Dev controller pointer fixes

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultLuminControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/GazeProvider.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TeleportPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json

Version 0.1.6

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityBoundaryVisualizationProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityCameraProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityDiagnosticsProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityRegisteredServiceProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultGenericOpenVRControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultGenericUnityControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultLuminControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultMouseControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusRemoteControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultTouchScreenControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultViveWandControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultWindowsMixedRealityControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultXboxControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerMappingProfiles.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerVisualizationProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityGesturesProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityInputActionRulesProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityInputActionsProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityInputPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityInputSystemProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealitySpeechCommandsProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Networking/DefaultMixedRealityNetworkingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/SpatialAwareness/DefaultMixedRealitySpatialAwarenessSystemProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/SpatialAwareness/DefaultWindowsMixedRealitySpatialMeshObserverProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json
XRTK.SDK/ProjectSettings/ProjectVersion.txt

Implements changes from https://github.com/XRTK/XRTK-Core/pull/157
- Blocked until `com.xrtk.core#0.1.10`

updated all of the default sdk profiles with new parent references.

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityBoundaryVisualizationProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityCameraProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityRegisteredServiceProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultGenericOpenVRControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultGenericUnityControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultMouseControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusRemoteControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultTouchScreenControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultViveWandControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultWindowsMixedRealityControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultXboxControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerVisualizationProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityGesturesProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityInputActionRulesProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealitySpeechCommandsProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Networking/DefaultMixedRealityNetworkingProfile.asset

Submodule PR for https://github.com/XRTK/XRTK-Core/pull/177

removed all the serialized values from the parent profiles

---

XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Scenes/BaseScene.unity
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json
XRTK.SDK/ProjectSettings/ProjectSettings.asset
XRTK.SDK/ProjectSettings/QualitySettings.asset

updated packages
updated serialization for project files

Bumped version to 0.1.8

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Collections/BaseObjectCollection.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Collections/GridObjectCollection.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Collections/ScatterObjectCollection.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Collections/BaseCollectionInspector.cs

- enabled undo actions
- enabled real-time in editor updates

updated object collections.

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/SpeechInputHandler.cs

Fixes speech event not being properly used.

Use speech event

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/BaseControllerPointerInspector.cs

Added the ability to specify if a pointer is on by default

Added the ability to specify if a pointer is on by default

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusGoControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusGoControllerMappingProfile.asset.meta
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerMappingProfiles.asset

OpenVR Oculus go supported profile updates

Adding default assets for Oculus go

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusGoControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusRemoteControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultViveWandControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultWindowsMixedRealityControllerMappingProfile.asset

Updated default controller mapping profiles to new class names in Core
https://github.com/XRTK/XRTK-Core/pull/213

Native oculus pre updates

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultViveWandControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerVisualizationProfile.asset

Visualization updates linked to Core Updates

Visualization updates linked to Core Updates

---

XRTK.SDK/Assets/csc.rsp
XRTK.SDK/Assets/csc.rsp.meta
XRTK.SDK/Packages/manifest.json
XRTK.SDK/ProjectSettings/ProjectSettings.asset
XRTK.SDK/ProjectSettings/ProjectVersion.txt

updated editor to 2019.1.9f1 and updated packages

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs

fixed a spelling error

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/BaseControllerPointerInspector.cs

Fixed the pointer locking to ensure the cursor and the end of the pointer line stays in place properly when locked.

Pointer Locking Fixes

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/BaseInputHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/BoundingBox/BoundingBox.cs

Fixed the bounding box to work as expected.
It even works with the manipulation handler!

Bounding Box Update

---

XRTK.SDK/Assets/XRTK.Generated/CustomProfiles/MixedRealityPackageSettings.asset
XRTK.SDK/Packages/manifest.json
XRTK.SDK/ProjectSettings/EditorBuildSettings.asset
XRTK.SDK/ProjectSettings/ProjectVersion.txt

updated editor to 2019.1.13f1
- Added xrtk.oculus package
- updated packages to latest versions

updated editor to 2019.1.13f1

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset

Fix oculus controller default mapping profile
- https://github.com/XRTK/XRTK-Core/pull/308

Fix oculus controller default mapping profile

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset

Updated Oculus Touch default mappings asset following Core updates.

Updated Oculus Touch default mappings asset following Core updates.

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultGenericOpenVRControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset

Trigger mapping update
Updates default asset in line with update to core OpenVR mappings

Trigger mapping update

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/SpatialAwareness/DefaultMixedRealitySpatialAwarenessSystemProfile.asset

Updated supported platforms for data providers from https://github.com/XRTK/XRTK-Core/pull/326

updated all the registered data providers with new platform flags

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusGoControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultViveWandControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultWindowsMixedRealityControllerMappingProfile.asset

Update the default asset mappings following a change in the core mapping definitions

Update default asset mappings

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset

updated mouse platform config

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset

Part of https://github.com/XRTK/XRTK-Core/pull/340

updated provider profile with new namespace changes

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/DragAndDropHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Tooltips/ToolTipSpawner.cs
XRTK.SDK/Packages/com.xrtk.sdk/XRTK.SDK.asmdef

removed a few unsued declarations

---

XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/XRTK.SDK.Inspectors.asmdef
XRTK.SDK/Packages/com.xrtk.sdk/XRTK.SDK.asmdef

updated assembly references to use guids

updated assembly references to use guids

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs

Updated the `ManipulationHandler` to utilize any type of `Collider`

updated manipulation handler to utilize any kind of collider

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs

[Fixed the thing I was concerned about in the last PR](https://github.com/XRTK/SDK/pull/99#discussion_r339273281)

Fixed snap position on manipulation handler

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs

Needed a way to specify a manipulation target in code.

Added public accessor for manipulation target

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/GazeProvider.cs
XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Scenes/BaseScene.unity

Updates Camera rig and associated scripts to use new Camera Rig Setup
* Update Gaze to use body
* Updated BaseScene
* Minor Config update as Oculus controller config was broken (OpenVR)
Depends on Core\#397
Requires #97

Updates to align with changes to Core CameraRig

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityCameraProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultOculusTouchControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/GazeProvider.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/InputSystemGlobalListener.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/TeleportCursor.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/MousePointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TeleportPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Scenes/BaseScene.unity
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json

- Updated some system awaiters to use the Awaiter.WaitUntil extension (#33)
- Fixed a problem where the manipulated object would stall when we didn't have snap to surface endabled (#98)
- Updated manipulation handler to utilize any kind of collider (#99)
- Fixed snap position on manipulation handler (#100)
- Added public accessor for manipulation target (#101)
- Dev/camera system updates (#97)

Release 0.1.16

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs

Better control of translation, rotations, and scaling.
You can now lock each transform type.

updated locks for translation, rotation, and scale

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultXboxControllerMappingProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TeleportPointer.cs

Fixed generic unity controller and open vr controller data provider registration priorities
Related to https://github.com/XRTK/XRTK-Core/pull/415

Updated input system data provider registrations

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Diagnostics/DefaultMixedRealityDiagnosticsSystemProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/ConsoleLogEntry.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/ConsoleLogEntry.prefab.meta
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/DefaultDiagnosticsWindow.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/Frame.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/Frame.prefab.meta
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityConsoleDiagnosticsHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityConsoleDiagnosticsHandler.cs.meta
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityConsoleDiagnosticsVisualizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityDiagnosticsWindow.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityDiagnosticsWindow.cs.meta
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityFrameDiagnosticsHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityFrameDiagnosticsHandler.cs.meta
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityFrameDiagnosticsVisualizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityMemoryDiagnosticsHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityMemoryDiagnosticsHandler.cs.meta
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Scripts/MixedRealityMemoryDiagnosticsVisualizer.cs

Continued from https://github.com/XRTK/XRTK-Core/pull/426

Change requests/diagnostics system update

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/DefaultDiagnosticsWindow.prefab

Updated the diagnostics prefab to make sure it's pretty and easily seen.
- Fixes: #123 
- Fixes: #122 
- Fixes: #119

cleaned up the diagnostics prefab a bit to make sure it looks nice

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/package.json

Updated the default data providers profile since the WMR data provider class name changed.

Fix default data providers profile due to name change

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/DefaultDiagnosticsWindow.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ControllerPoseSynchronizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/InputSystemGlobalListener.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/BoundingBox/BoundingBox.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/CursorModifier.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json

Release 0.1.19

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Diagnostics/Prefabs/DefaultDiagnosticsWindow.prefab

Using the editor updated diagnostics prefab to try and resolve the package issue

Using the editor updated diagnostics prefab to try and resolve the package issue

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityToolkitRootProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/SdkPathFinder.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/SdkPathFinder.cs.meta
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/XRTK.SDK.Inspectors.asmdef

Continued from https://github.com/XRTK/XRTK-Core/pull/489

Added SdkPathFinder

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ControllerPoseSynchronizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/BaseHandControllerVisualizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/HandControllerJointsVisualizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/HandControllerMeshVisualizer.cs

https://github.com/XRTK/XRTK-Core/pull/497

updated references

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ControllerPoseSynchronizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/DefaultMixedRealityControllerVisualizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/BaseHandControllerVisualizer.cs

https://github.com/XRTK/XRTK-Core/pull/514

updated handler references

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/DefaultMixedRealityRegisteredServiceProvidersProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Diagnostics/DefaultMixedRealityDiagnosticsSystemProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/SpatialAwareness/DefaultMixedRealitySpatialAwarenessSystemProfile.asset

updated service configurations
https://github.com/XRTK/XRTK-Core/pull/521

Platform Refactor

---

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Diagnostics/DefaultMixedRealityDiagnosticsSystemProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/DefaultMixedRealityControllerDataProvidersProfile.asset

https://github.com/XRTK/XRTK-Core/pull/535

fixed profile runtime platform definitions

---

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TeleportPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/Input/Handlers/ControllerPoseSynchronizerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/BaseControllerPointerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/LinePointerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/MousePointerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/ParabolicTeleportPointerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Inspectors/UX/Pointers/TeleportPointerInspector.cs

https://github.com/XRTK/XRTK-Core/pull/540

updated inspector to use new bold foldout property drawer

---

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/LeftGenericOpenVRControllerProfile.asset

https://github.com/XRTK/XRTK-Core/pull/561

fixed left generic controller type reference

---

XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs

updated sdk packages installer to be more similar to the other installers in other packages
https://github.com/XRTK/XRTK-Core/pull/571

Change requests/sdk installer

---

XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs

Updated GUID regeneration for SDK
- Fixes: #172
- https://github.com/XRTK/XRTK-Core/pull/569

Updated GUID regeneration for SDK

---

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

Now using triggers for pointer near interaction.
https://github.com/XRTK/XRTK-Core/pull/577

Use triggers for pointer collision

---

XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs

Continued from https://github.com/XRTK/XRTK-Core/pull/592
Fixed inverted flag on validation check

Updated package installer

---

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/Left/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/Right/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusGoController/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Left/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Right/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/ViveWandController/Left/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/ViveWandController/Right/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/InvertDualAxisProcessor.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/ThumbstickPositionProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/TriggerPress(Select)Profile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/GripPressProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/InvertDualAxisProcessor.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/SpatialPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/TriggerPress(Select)Profile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/Pointers/TeleportPointerProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/Pointers/TeleportPointerProfile.asset.meta

- Added teleport pointers to all controllers that support it.
- Updated wmr controller actions and references

Updated teleport pointer references on controllers, fixed wmr input

---

XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/MousePointerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Cursors/MouseCursor.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/MousePointer.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/MeshCursor.cs
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/MousePointer.cs

- Updated the mouse pointer to toggle on/off as simulated hand input is detected/lost.
- Fixed mouse pointer inspector showing duplicate entry
- Updated mesh cursor to keep constant size so the mouse cursor stays the same size at any distance

Mouse input/visual polish

---

XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/BaseControllerPointerInspector.cs
XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/DefaultControllerPointer.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/MousePointer.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/ParabolicPointer.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/TouchPointer.prefab
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

https://github.com/XRTK/XRTK-Core/pull/618

Added InteractionMode to pointers

---

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/ControllerPoseSynchronizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/Hands/BaseHandControllerVisualizer.cs
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
XRTK.SDK/Packages/manifest.json

https://github.com/XRTK/XRTK-Core/pull/621

updated null and destroy calls with better extension

---

azure_pipelines/stages/publish.yml
azure_pipelines/stages/steps/build-unity-player.yml
azure_pipelines/stages/steps/export-package-seed.yml
azure_pipelines/stages/steps/install-unity.yml
azure_pipelines/stages/steps/return-unity-license.yml
azure_pipelines/stages/steps/run-unity-tests.yml
azure_pipelines/stages/steps/upm-package-info.yml
azure_pipelines/stages/unity-build.yml

Sync pipeline changes from core

---

XRTK.SDK/Packages/manifest.json
azure_pipelines/stages/steps/install-unity.yml

Fixes build pipeline module installation

fixes module installation

---

XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/Diagnostics/DefaultDiagnosticsWindow.prefab

Fixed asset serialization for text mesh pro assets on diagnostics window prefab.

fixed asset assignments for tmp diagnostics window

---

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/MixedRealityToolkitRootProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json
XRTK.SDK/Packages/packages-lock.json

Changes from https://github.com/XRTK/XRTK-Core/pull/705

re-serialized value for boundary system profile

---

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportSystemProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportValidationDataProviderProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportValidationDataProviderProfile.asset.meta
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/TeleportCursor.cs
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/TeleportPointer.cs
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json

Please see https://github.com/XRTK/XRTK-Core/pull/727

Introduce teleport validation data provider

---

XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json
XRTK.SDK/Packages/packages-lock.json
XRTK.SDK/ProjectSettings/ProjectVersion.txt

updated project to 2019.4.17f1

updated project to 2019.4.17f1

---

XRTK.SDK/Packages/com.xrtk.sdk/LICENSE.md
XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/Simulated/SimulatedHandControllerDataProviderProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/packages-lock.json

https://github.com/XRTK/XRTK-Core/pull/767

Implement grip threshold profile setting

---

azure-pipelines.yml

Temporarily remove the webxr build from CI/CD until the feature is complete

Temp remove webxr build from CI/CD

---

XRTK.SDK/Packages/com.xrtk.sdk/package.json
XRTK.SDK/Packages/manifest.json
XRTK.SDK/Packages/packages-lock.json
XRTK.SDK/ProjectSettings/ProjectVersion.txt

- bumped editor version to 2019.4.21f1 to match core
- updated to the latest packages
- Fixes: #231

Bumped editor version to 2019.4.21f1

---

XRTK.SDK/Packages/com.xrtk.sdk/Editor/AssemblyInfo.cs
XRTK.SDK/Packages/com.xrtk.sdk/Editor/AssemblyInfo.cs.meta
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/AssemblyInfo.cs
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/AssemblyInfo.cs.meta

Adding compiler definitions for platforms
- https://github.com/XRTK/XRTK-Core/pull/839

Adding compiler definitions for platforms

---

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/LocomotionSystem/BlinkTeleportLocomotionProviderProfile.asset
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/StandardAssets/Materials/Standard/Standard_TransparentBlack.mat
XRTK.SDK/Packages/com.xrtk.sdk/Runtime/StandardAssets/Materials/Standard/Standard_TransparentBlack.mat.meta

See https://github.com/XRTK/com.xrtk.core/pull/894
- Added new standard material in SDK Black with transparency enabled
- Updated profile for blink teleport data provider
- https://github.com/XRTK/com.xrtk.core/pull/894

Create standard assets for new profile property

---

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

Fixes the issue where a controller pointer would not have a cursor even though a prefab was configured, because the locomotion system is not available.

Fix pointer cursor not set when locomotion system is not available
