XRTK/com.xrtk.sdk

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/GazeProvider.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/LinePointer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/TeleportPointer.cs, XRTK.SDK/Packages/manifest.json
Finishes up https://github.com/XRTK/XRTK-Core/pull/149
=> Dev focus updates

XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/Wireframe.mat, XRTK.SDK/Packages/com.xrtk.sdk/StandardAssets/Materials/WireframeBlue.mat
Update Wireframe materials to use new wireframe shader from MRTK
- Updates materials to use the new wireframe shader in core #253
=> Update Wireframe materials to use new wireframe shader from MRTK

XRTK.SDK/Packages/com.xrtk.sdk/DefaultProfiles/Input/ControllerMappings/DefaultWindowsMixedRealityControllerMappingProfile.asset
Resolves mapping issue where the Axis for Trigger Touch was incorrect in the default asset for the WMR OpenVR Controller
Asset regenerated and Axis fixed for default asset
=> Resolves mapping issue where the Axis for Trigger Touch was incorrect in the default asset

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
- Snapping was improperly using the transform to do the world space/local space translations.
- Bounds center and size was incorrect. Used Collider size and center instead.
=> Properly snap

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
Needed to provide a way for developers to choose if they wanted to grab and manipulate the object by the origin or by the pointer's grab position.
=> Choose to use pointer offset position or origin when grabbing

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs
Fixed a problem where the manipulated object would stall when the physics sweep happens when we didn't have snap to surface enabled
=> Fix physics sweeping when not snapped

XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Pointers/MousePointer.cs
updated the mouse pointers `CameraCache` reference with the new `CameraSystem.CameraRig.Camera` reference.
=> updated mouse pointer's CameraCache reference

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/InputSystemGlobalListener.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Cursors/BaseCursor.cs
Input system global listener sometimes doesn't unregister a global listener if the object is destroyed outright and disable isn't called first
=> Fixed global listener unregistration 

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/InputSystemGlobalListener.cs
Removed the abstract modifier. This allows to attach `InputSystemGlobalListener` to game objects on its own.
- Resolves: #128
=> Make input system global listener non abstract

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ManipulationHandler.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/BoundingBox/BoundingBox.cs, XRTK.SDK/Packages/com.xrtk.sdk/package.json, XRTK.SDK/Packages/manifest.json
Continuation of https://github.com/XRTK/XRTK-Core/pull/448
- update all the usages of `Transform.SetCollidersActive`
- only update transform bounds if collider is set
=> Transform Extension Collider and Bounds Calculation Performance Update

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/Handlers/ControllerPoseSynchronizer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/BaseHandControllerVisualizer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/HandControllerJointsVisualizer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Features/UX/Scripts/Controllers/Hands/HandControllerMeshVisualizer.cs
https://github.com/XRTK/XRTK-Core/pull/501
=> updated base hand visualizer to use the controller data provider reference

XRTK.SDK/Packages/com.xrtk.sdk/Features/Input/GazeProvider.cs
When running the XRTK without a camera system, the Main Camera is no longer parented under the Mixed Reality Playspace. If the Input System is on, then it'll throw Null Refs.
=> Fixed a NRE when the GazeProvider doesn't have a parent

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/CameraSystem/MixedRealityCameraDataProviderProfile.asset
Updates the default near clip plane distance to 0.2 for transparent displays.
=> Update default near clip plane for transparent display

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/MousePointer.cs
Use gameobject.name for pointer
- Better events when clicking in and out of the editor/application window with mouse
- Updated `BaseControllerPointer` to just use the gameobject name for the pointer
=> A few more tweaks to the mouse pointer

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/Hands/DefaultHandControllerVisualizer.cs, XRTK.SDK/Packages/com.xrtk.sdk/package.json, XRTK.SDK/Packages/manifest.json
Please see https://github.com/XRTK/XRTK-Core/pull/677
=> Rename HandBoundsMode to HandBoundsLOD for better understanding

XRTK.SDK/Packages/com.xrtk.sdk/Editor/SDKPackageInstaller.cs
Just removed the "XRTK." prefix from the SDK package installer for consistency with all other platforms.
=> Remove XRTK prefix from SDK package installer

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/ManipulationHandler.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Controllers/Hands/DefaultHandControllerVisualizer.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, XRTK.SDK/Packages/com.xrtk.sdk/package.json, XRTK.SDK/Packages/manifest.json, XRTK.SDK/Packages/packages-lock.json
Changes from https://github.com/XRTK/XRTK-Core/pull/710
=> fixed invalid namesapce

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/Left/GripTriggerPositionProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/GenericOpenVRController/Right/GripTriggerPositionProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/CommonInteractionMappingProfiles/LeftHandGripInteractionMappingProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/CommonInteractionMappingProfiles/RightHandGripInteractionMappingProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/HandControllers/Simulated/RightSimulatedMixedRealityHandControllerProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Left/Axis1D.PrimaryHandTriggerPressProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Left/Axis1D.PrimaryHandTriggerProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Right/Axis1D.SecondaryHandTriggerPressProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/OculusTouchController/Right/Axis1D.SecondaryHandTriggerProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/ViveWandController/Left/GripPressProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/ViveWandController/Right/GripPressProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Left/GripPressProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/DataProviders/WindowsMixedRealityController/Right/GripPressProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Input/MixedRealityInputActionsProfile.asset
There was some inconsistency with grip related input actions, which I cleaned up. Also I updated all existing and supported controllers to use the now properly named grip input actions. From now on there shall be 3 grip related input actions:
- Grip Press: Digital, has the grip button been pressed to its full extend or not?
- Grip Pose: 6DoF, where to attach things I grabbed using the controller?
- Grip Strength: Single Axis, how strong is my grip?
- [Lumin](https://github.com/XRTK/Lumin/pull/92)
- [Oculus](https://github.com/XRTK/Oculus/pull/98)
- [WMR](https://github.com/XRTK/WindowsMixedReality/pull/110)
- [Examples](https://github.com/XRTK/Examples/pull/18)
=> Clean up grip related input actions

XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/MixedRealityToolkitRootProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport.meta, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportSystemProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportSystemProfile.asset.meta, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/Input/Handlers/TeleportHotSpot.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem.meta, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem/BaseTeleportHandler.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem/BaseTeleportHandler.cs.meta, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem/FadingTeleportHandler.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem/FadingTeleportHandler.cs.meta, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem/InstantTeleportHandler.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/TeleportSystem/InstantTeleportHandler.cs.meta, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Cursors/TeleportCursor.cs, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, XRTK.SDK/Packages/com.xrtk.sdk/package.json
Please see https://github.com/XRTK/XRTK-Core/pull/722
- [Core](https://github.com/XRTK/XRTK-Core/pull/722)
- [Examples](https://github.com/XRTK/Examples/pull/19)
=> Teleport System v2

XRTK.SDK/Packages/com.xrtk.sdk/Editor/UX/Pointers/TeleportPointerInspector.cs, XRTK.SDK/Packages/com.xrtk.sdk/Prefabs~/UX/Pointers/ParabolicPointer.prefab, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportSystemProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Profiles~/Teleport/MixedRealityTeleportValidationDataProviderProfile.asset, XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/TeleportPointer.cs, XRTK.SDK/Packages/com.xrtk.sdk/package.json
Companion PR to https://github.com/XRTK/XRTK-Core/pull/729
=> Allow Digital and SingleAxis input actions for teleport

XRTK.SDK/Packages/com.xrtk.sdk/Runtime/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
The `BaseControllerPointer` had a hard dependency on the Locomotion System left. I noticed in a project where I removed the system completely from the XRTK root profile because I don't need it, that a NRE is fired because the system is not available.
This PR addresses that.
=> Fix NRE in BaseControllerPointer when locomotion system is not available

XRTK.SDK/Packages/com.xrtk.sdk/Editor/Input/Handlers/ControllerPoseSynchronizerInspector.cs
The serialized `destroyOnSourceLost` field was not exposed in the inspector for `ControllerPoseSynchronizer` / Controller Visualizer and there was no way of changing it in a prefab.
=> Fix destroyOnSourceLost not exposed in controller visualizer inspector
